name: validicityclient
description: The client running on a Linux box scanning NFC tags
version: 0.1.0
author: Göran Krampe <goran.krampe@gmail.com>

environment:
  sdk: '>=2.7.1'

executables:  
  validicityclient: validicityclient

dependencies:
  async:
  args: ^1.5.2
  http: ^0.12.0+4
  logging: ^0.11.3+2

  validicitylib:
    path: ../validicitylib

